modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT License"

[[mods]]
modId = "hydrogenmod"
version = "2.0.0"
displayName = "HydrogenMod"
displayURL = "https://github.com/stouma915/HydrogenMod"
credits = "Idea by bikikiMK2, Programmed by stouma915, Block model by Blockbench"
authors = "stouma915, bikikiMK2"
description = "Minecraftに水素を追加するMod"

[[dependencies.hydrogenmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5]"
ordering = "NONE"
side = "BOTH"
