name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Avoid timestamp error
      run: |
        wget https://repo1.maven.org/maven2/org/typelevel/simulacrum-scalafix-annotations_3.0.0-M3/0.5.3/simulacrum-scalafix-annotations_3.0.0-M3-0.5.3.jar
        mv simulacrum-scalafix-annotations_3.0.0-M3-0.5.3.jar simulacrum-scalafix-annotations_3-0.5.4.jar
        cp simulacrum-scalafix-annotations_3-0.5.4.jar /home/runner/.gradle/caches/modules-2/files-2.1/org.typelevel/simulacrum-scalafix-annotations_3/0.5.4/e7ac3b68838b3905c9bdc4a870ec54a4bee2cf88/
    - name: Build
      run: bash gradlew build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hydrogenmod
        path: build/libs/hydrogenmod-*.jar
